version: 2  
updates:  
   
  - package-ecosystem: "pip"  
    directory: "/"
    schedule:  
      interval: "daily"   
    commit-message:  
      prefix: "fix"   

   
  - package-ecosystem: "github-actions"  
    directory: "/workflows/" 
    schedule:  
      interval: "weekly" 
