[tool.black]
line-length = 100
target-version = ['py39', 'py310', 'py311', 'py312', 'py313']
skip-string-normalization = true
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.bandit]
disable = ["B404", "B311", "B603"]
