name: "Issue Auto Response"
on:
  issues:
    types: [opened]

permissions:
  contents: read
  issues: write
  pull-requests: write
  actions: read

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: "Comment on new issues"
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Thanks for your report! We'll review it soon."
            });
