name: Changelog Generator

on:
  push:
    branches:
      - main

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    environment: cyberspace
    permissions:
      contents: write

    steps:
      - name:  Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name:  Install git-cliff
        run: |
          # Get latest release URL using GitHub API
          CLIFF_URL=$(curl -s https://api.github.com/repos/orhun/git-cliff/releases/latest | 
            grep "browser_download_url.*x86_64-unknown-linux-gnu.tar.gz" | 
            cut -d '"' -f 4)
          
          # Download and install with cyberpunk flair
          curl -sSL $CLIFF_URL -o git-cliff.tar.gz
          tar -xzf git-cliff.tar.gz
          sudo mv git-cliff-*/git-cliff /usr/local/bin/
          rm -rf git-cliff*

      - name:  Generate CHANGELOG.md
        run: |
          # Create hacker-style config
          echo '
          [changelog]
          header = "󰓅 CHANGELOG\n==========\n\n󰭻 All system changes documented below 󰭻\n\n"
          footer = "\n\n󰓼 Generated by [git-cliff](https://github.com/orhun/git-cliff) 󰓼"
          
          [git]
          conventional_commits = true
          commit_parsers = [
              { message = "^feat", group = " Features" },
              { message = "^fix", group = " Fixes" },
              { message = "^docs", group = "  Documentation" },
              { message = "^refactor", group = " Refactors" },
              { message = "^chore", group = " Maintenance" },
              { message = "^test", group = " Tests" },
          ]

          [template]
          body = """
          ## 󰄵 {{ version }} - {{ timestamp | date(format="%Y-%m-%d") }}\n
          {% for group, commits in commits | group_by(attribute="group") %}
          ### {% match group %}
            {% when  Features" %}{% when " Fixes" %}{% when " Documentation" %}{% when " Refactors" %}{% when " Maintenance" %}{% else %}{% endmatch %} {{ group }}\n
          {% for commit in commits %}
          - {% match group %}
              {% when " Features" %}{% when " Fixes" %}{% when " Documentation" %}{% when " Refactors" %}{% when " Maintenance" %}{% else %}󰡀{% endmatch %} 
              {{ commit.message | upper_first }} 
              (󰜢 [{{ commit.id | truncate(length=7, end="") }}](https://github.com/${{ github.repository }}/commit/{{ commit.id }}))\n
          {% endfor %}
          {% endfor %}
          """' > cyberpunk.toml

          # Generate the changelog
          git-cliff --unreleased --config cyberpunk.toml -o CHANGELOG.md

      - name:  Commit Changes
        run: |
          git config --global user.name "󱓞 Changelog Bot"
          git config --global user.email "sysadmin@neural.link"
          
          if git diff --quiet CHANGELOG.md; then
            echo "No changelog updates required"
          else
            git add CHANGELOG.md
            git commit -m "Update cyberlog: $(date +'%Y-%m-%d %H:%M:%S')"
            git push
          fi
