name: Close Stale Issues
on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Close Stale Issues
        uses: actions/stale@v9.0.0
        with:
          stale-issue-message: "This issue has been automatically marked as stale because it has not had recent activity. If you believe this issue is still relevant, please leave a comment."
          stale-pr-message: "This pull request has been marked as stale due to inactivity. It will be closed if no further updates are provided."
          days-before-stale: 30
          days-before-close: 7
          exempt-issue-labels: |
            keep open
          exempt-pr-labels: |
            wip
