name: Unit Test

on:
  schedule:
    - cron: '0 */3 * * *'  
  push:
    branches:
      - main   
    paths:
      - 'tests/**'      
      - 'main.py'     # Trigger when 'main.py' file is changed
  pull_request:
    branches:
      - main   # Trigger on PRs to the main branch
    paths:
      - 'tests/**'    
      - 'main.py'
jobs:
  build:
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    permissions:
      actions: read
      contents: read
      statuses: write
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5.5.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || pip install --no-cache-dir -r requirements.txt

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-

      
      - name: Run Unit Tests
        run: |
          python -m unittest tests/test_minor.py
          python -m unittest tests/test_poke.py
          python -m unittest tests/test_checker.py
